name: Test Notebooks

on:
  push:
    branches: [ main, development, experimental ]
  pull_request:
    branches: [ main, development, experimental ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install xlrd==1.2.0
        pip install nbmake # installs pytest too

        pip install matplotlib pyneuroml

    - name: Test Notebooks
      run: |
        pytest -v --nbmake TestLoadingData.ipynb

        echo "============    Testing nb 2   ==========="
        
        pytest -v --nbmake TestCanonicalPositions.ipynb


    - name: Final version info
      run: |
        pip list
